apiVersion: v1
kind: Service
metadata:
  name: sentinel-ai
  namespace: default
  labels:
    app: sentinel-ai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: sentinel-ai
